/* Every word on the new-patient form (/register) and its QR poster, in English, Gujarati and
   Hindi. One table so someone who reads Gujarati / Hindi can correct the wording in one place.
   Some lines are taken from the WhatsApp intake scripts (whatsapp-intake/clinics/gurukrupa.yaml).
   `{name}` / `{age}` are filled in by t(). A missing key falls back to English. */

export const UI_LANGS = [
  { key: 'en', label: 'English' },
  { key: 'gu', label: 'ગુજરાતી' },
  { key: 'hi', label: 'हिन्दी' },
];

export const STRINGS = {
  en: {
    languageSwitch: 'Language',
    hospitalLocal: 'Guru Krupa Eye Hospital',
    title: 'New patient form',
    firstVisitOnly: 'For first visits only.',
    beenBefore: 'Been here before? Please tell the reception desk instead.',
    intro: 'Take your time. Only your name and mobile number are needed; the rest helps the doctor.',
    needed: 'needed',
    qName: 'Your full name',
    qNamePh: 'Full name',
    qPhone: 'Mobile number',
    qPhoneHelp: '10-digit mobile number, e.g. 9876543210',
    qDob: 'Date of birth',
    qAge: 'Age, if date of birth not known',
    qAgePh: 'Age in years',
    ageFromDob: 'Age {age} years from the date of birth',
    dobProblem: 'Please check the date of birth.',
    qSex: 'Sex',
    sexF: 'Female',
    sexM: 'Male',
    sexO: 'Other',
    qAddress: 'Address',
    qAddressPh: 'Area, city',
    qOccupation: 'Occupation',
    qOccupationPh: 'e.g. teacher, business, homemaker',
    qScreen: 'Screen time (mobile, TV, computer)',
    qScreenPh: 'Hours a day',
    qConditions: 'Do you have any of these illnesses?',
    qConditionsHelp: 'Tick all that apply.',
    qConditionOther: 'Any other illness',
    qLanguage: 'Which language do you prefer?',
    qHeard: 'How did you hear about us?',
    qReferrerDoctor: 'Name of the doctor who sent you',
    qReferrer: 'Who sent you?',
    qElsewhere: 'Have you had eye treatment at another hospital before?',
    yes: 'Yes',
    no: 'No',
    qElsewhereNote: 'Where, and for what? e.g. cataract operation, Rajkot, 2 years ago',
    elsewhereBring: 'If you have old prescriptions or reports, please show them at the desk.',
    submit: 'Send my details',
    submitting: 'Sending…',
    errName: 'Please write your name.',
    errPhone: 'Please write a 10-digit mobile number, e.g. 9876543210.',
    errGeneric: 'Could not send the form. Please try again, or ask at the reception desk.',
    errRate: 'Too many forms from this phone. Please ask at the reception desk.',
    thanksTitle: 'Thank you, {name}',
    thanksBody: 'Your details have been sent.',
    tokenLabel: 'Your token number',
    tokenHelp: 'Please show this number at the reception desk.',
    another: 'Fill for another person',
    posterHeadline: 'New patient? Scan to fill your details',
    posterFirstVisit: 'First visit only. Been here before? Please tell the reception desk.',
  },
  gu: {
    languageSwitch: 'ભાષા',
    hospitalLocal: 'ગુરુ કૃપા આઈ હોસ્પિટલ',
    title: 'નવા દર્દી માટેનું ફોર્મ',
    firstVisitOnly: 'ફક્ત પહેલી વાર આવતા દર્દીઓ માટે.',
    beenBefore: 'પહેલાં અહીં આવી ગયા છો? તો કૃપા કરીને રિસેપ્શન પર જણાવો.',
    intro: 'કોઈ ઉતાવળ નથી. ફક્ત નામ અને મોબાઇલ નંબર જરૂરી છે; બાકીની માહિતી ડૉક્ટરને મદદરૂપ થશે.',
    needed: 'જરૂરી',
    qName: 'તમારું પૂરું નામ',
    qNamePh: 'પૂરું નામ',
    qPhone: 'મોબાઇલ નંબર',
    qPhoneHelp: '10 આંકડાનો mobile number, જેમ કે 9876543210',
    qDob: 'જન્મ તારીખ',
    qAge: 'ઉંમર, જો જન્મ તારીખ ખબર ન હોય તો',
    qAgePh: 'ઉંમર (વર્ષ)',
    ageFromDob: 'જન્મ તારીખ પ્રમાણે ઉંમર {age} વર્ષ',
    dobProblem: 'કૃપા કરીને જન્મ તારીખ ફરી તપાસો.',
    qSex: 'જાતિ',
    sexF: 'સ્ત્રી',
    sexM: 'પુરુષ',
    sexO: 'અન્ય',
    qAddress: 'સરનામું',
    qAddressPh: 'વિસ્તાર, શહેર',
    qOccupation: 'વ્યવસાય',
    qOccupationPh: 'જેમ કે શિક્ષક, વેપાર, ગૃહિણી',
    qScreen: 'સ્ક્રીન સમય (મોબાઇલ, ટીવી, કમ્પ્યુટર)',
    qScreenPh: 'દિવસના કેટલા કલાક',
    qConditions: 'તમને આમાંથી કોઈ બીમારી છે?',
    qConditionsHelp: 'લાગુ પડતી બધી પર ટિક કરો.',
    qConditionOther: 'બીજી કોઈ બીમારી',
    qLanguage: 'તમને કઈ ભાષા વધુ ફાવે છે?',
    qHeard: 'તમને અમારા વિશે કેવી રીતે ખબર પડી?',
    qReferrerDoctor: 'તમને મોકલનાર ડૉક્ટરનું નામ',
    qReferrer: 'તમને કોણે મોકલ્યા?',
    qElsewhere: 'પહેલાં બીજી કોઈ હોસ્પિટલમાં આંખની સારવાર કરાવી છે?',
    yes: 'હા',
    no: 'ના',
    qElsewhereNote: 'ક્યાં અને શેની? જેમ કે મોતિયાનું ઓપરેશન, રાજકોટ, 2 વર્ષ પહેલાં',
    elsewhereBring: 'જૂની દવાની ચિઠ્ઠી કે રિપોર્ટ હોય તો રિસેપ્શન પર બતાવશો.',
    submit: 'મારી વિગતો મોકલો',
    submitting: 'મોકલી રહ્યા છીએ…',
    errName: 'કૃપા કરીને તમારું નામ લખો.',
    errPhone: 'માફ કરજો, 10 આંકડાનો mobile number લખશો? જેમ કે 9876543210',
    errGeneric: 'ફોર્મ મોકલી શકાયું નહીં. ફરી પ્રયત્ન કરો, અથવા રિસેપ્શન પર પૂછો.',
    errRate: 'આ ફોનથી ઘણાં ફોર્મ આવી ગયાં છે. કૃપા કરીને રિસેપ્શન પર પૂછો.',
    thanksTitle: 'આભાર, {name}',
    thanksBody: 'બસ, થઈ ગયું! તમારી વિગતો મળી ગઈ છે.',
    tokenLabel: 'તમારો ટોકન નંબર',
    tokenHelp: 'કૃપા કરીને આ નંબર રિસેપ્શન પર બતાવો.',
    another: 'બીજી વ્યક્તિ માટે ફોર્મ ભરો',
    posterHeadline: 'નવા દર્દી છો? તમારી વિગતો ભરવા માટે scan કરો',
    posterFirstVisit: 'ફક્ત પહેલી વાર માટે. પહેલાં આવી ગયા છો? તો રિસેપ્શન પર જણાવો.',
  },
  hi: {
    languageSwitch: 'भाषा',
    hospitalLocal: 'गुरु कृपा आई हॉस्पिटल',
    title: 'नए मरीज़ का फ़ॉर्म',
    firstVisitOnly: 'सिर्फ़ पहली बार आने वाले मरीज़ों के लिए।',
    beenBefore: 'पहले यहाँ आ चुके हैं? तो कृपया रिसेप्शन पर बताइए।',
    intro: 'कोई जल्दी नहीं है। सिर्फ़ नाम और मोबाइल नंबर ज़रूरी है; बाकी जानकारी डॉक्टर के काम आएगी।',
    needed: 'ज़रूरी',
    qName: 'आपका पूरा नाम',
    qNamePh: 'पूरा नाम',
    qPhone: 'मोबाइल नंबर',
    qPhoneHelp: '10 अंकों का mobile number, जैसे 9876543210',
    qDob: 'जन्म तिथि',
    qAge: 'उम्र, अगर जन्म तिथि पता न हो',
    qAgePh: 'उम्र (साल)',
    ageFromDob: 'जन्म तिथि के हिसाब से उम्र {age} साल',
    dobProblem: 'कृपया जन्म तिथि दोबारा देखिए।',
    qSex: 'लिंग',
    sexF: 'महिला',
    sexM: 'पुरुष',
    sexO: 'अन्य',
    qAddress: 'पता',
    qAddressPh: 'इलाका, शहर',
    qOccupation: 'काम / व्यवसाय',
    qOccupationPh: 'जैसे शिक्षक, व्यापार, गृहिणी',
    qScreen: 'स्क्रीन टाइम (मोबाइल, टीवी, कंप्यूटर)',
    qScreenPh: 'दिन में कितने घंटे',
    qConditions: 'क्या आपको इनमें से कोई बीमारी है?',
    qConditionsHelp: 'जो लागू हों, सब पर टिक करें।',
    qConditionOther: 'कोई और बीमारी',
    qLanguage: 'आपको कौन-सी भाषा ज़्यादा सुविधाजनक है?',
    qHeard: 'आपको हमारे बारे में कैसे पता चला?',
    qReferrerDoctor: 'आपको भेजने वाले डॉक्टर का नाम',
    qReferrer: 'आपको किसने भेजा?',
    qElsewhere: 'क्या पहले किसी और अस्पताल में आँखों का इलाज करवाया है?',
    yes: 'हाँ',
    no: 'नहीं',
    qElsewhereNote: 'कहाँ और किस चीज़ का? जैसे मोतियाबिंद का ऑपरेशन, राजकोट, 2 साल पहले',
    elsewhereBring: 'पुरानी पर्ची या रिपोर्ट हो तो रिसेप्शन पर दिखाइए।',
    submit: 'मेरी जानकारी भेजें',
    submitting: 'भेज रहे हैं…',
    errName: 'कृपया अपना नाम लिखिए।',
    errPhone: 'माफ़ कीजिए, 10 अंकों का mobile number लिखेंगे? जैसे 9876543210',
    errGeneric: 'फ़ॉर्म नहीं भेजा जा सका। फिर से कोशिश करें, या रिसेप्शन पर पूछें।',
    errRate: 'इस फ़ोन से बहुत सारे फ़ॉर्म आ चुके हैं। कृपया रिसेप्शन पर पूछिए।',
    thanksTitle: 'धन्यवाद, {name}',
    thanksBody: 'बस, हो गया! आपकी जानकारी मिल गई है।',
    tokenLabel: 'आपका टोकन नंबर',
    tokenHelp: 'कृपया यह नंबर रिसेप्शन पर दिखाइए।',
    another: 'किसी और के लिए फ़ॉर्म भरें',
    posterHeadline: 'नए मरीज़ हैं? अपनी जानकारी भरने के लिए scan करें',
    posterFirstVisit: 'सिर्फ़ पहली बार के लिए। पहले आ चुके हैं? तो रिसेप्शन पर बताइए।',
  },
};

/* The admin-configured lists (referral sources, conditions) arrive in English. These give the
   seeded labels in Gujarati / Hindi, looked up by the English label; a label added or renamed
   in Admin simply shows as typed. */
export const LIST_LABELS = {
  gu: {
    'Self / Walk-in': 'જાતે / સીધા આવ્યા',
    'Referred by another doctor': 'બીજા ડૉક્ટરે મોકલ્યા',
    'Referred by family / another patient': 'મિત્ર / કુટુંબ કે બીજા દર્દીએ કહ્યું',
    'Online / Google': 'ઓનલાઇન / ગૂગલ',
    'Insurance / TPA': 'વીમો / TPA',
    'Camp / Outreach': 'કેમ્પ',
    Diabetes: 'ડાયાબિટીસ (સુગર)',
    Hypertension: 'હાઈ બ્લડ પ્રેશર',
    Asthma: 'દમ / અસ્થમા',
    Arthritis: 'સાંધાનો દુખાવો',
    'Thyroid disorder': 'થાઇરોઇડ',
    'Heart disease / stroke history': 'હૃદય રોગ / લકવો',
    Allergy: 'એલર્જી',
    'Acidity / GERD': 'એસિડિટી',
    BPH: 'પ્રોસ્ટેટ (BPH)',
  },
  hi: {
    'Self / Walk-in': 'खुद / सीधे आए',
    'Referred by another doctor': 'दूसरे डॉक्टर ने भेजा',
    'Referred by family / another patient': 'दोस्त / परिवार या दूसरे मरीज़ ने बताया',
    'Online / Google': 'ऑनलाइन / गूगल',
    'Insurance / TPA': 'बीमा / TPA',
    'Camp / Outreach': 'कैंप',
    Diabetes: 'डायबिटीज़ (शुगर)',
    Hypertension: 'हाई ब्लड प्रेशर',
    Asthma: 'दमा / अस्थमा',
    Arthritis: 'जोड़ों का दर्द (गठिया)',
    'Thyroid disorder': 'थायरॉइड',
    'Heart disease / stroke history': 'दिल की बीमारी / लकवा',
    Allergy: 'एलर्जी',
    'Acidity / GERD': 'एसिडिटी',
    BPH: 'प्रोस्टेट (BPH)',
  },
};

/** `t('en', 'thanksTitle', { name: 'Asha' })` -> 'Thank you, Asha'. */
export function t(lang, key, vars) {
  let s = STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
  if (vars) Object.entries(vars).forEach(([k, v]) => (s = s.replaceAll(`{${k}}`, String(v))));
  return s;
}

/** An admin-list label in the chosen language (falls back to the label as typed). */
export function listLabel(lang, label) {
  return LIST_LABELS[lang]?.[label] ?? label;
}
